services:
    dev:
        build: .
        image: hyperwin/hyperosbuildenv:latest
        environment:
            - DISPLAY
        hostname: hyperosbuildenv
        volumes:
            - .:/hyperos
        working_dir: '/hyperos'
        network_mode: 'host'
        entrypoint: []
